language: node_js
node_js:
 - "4.2"

install:
 - npm install --production
 - npm install browserify node-lessify uglifyify

script:
 - echo world

after_success:
 - npm run merge
 - sshpass -p $DEPLOY_PASSWORD scp  -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null dist/allin1.html $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
 - echo done