group: deprecated-2017Q4
language: android
android:
 components:
  - build-tools-23.0.2
  - android-22

addons:
 apt:
  packages:
   - sshpass

before_install:
 - echo "install nodejs"
 - nvm install 8
 - npm install yarn -g
 - node --version
 - npm --version
 - nvm --version

install:
 - yarn install

script:
 - yarn build.$BUILD_MODE
 - yarn cordova -- --storePassword=$STORE_PWD --password=$STORE_PWD

after_success:
 - mv cordova/platforms/android/build/outputs/apk/android-release.apk ./app.apk
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME/app.apk "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

 - node -p "require('./package.json').version" > dist/app.apk.version
 - mv dist $APP_NAME
 - rm $APP_NAME/index.tmpl
 - rm $APP_NAME/config.xml
 - cd $APP_NAME
 - tar cvfz ../$APP_NAME.tgz .
 - cd ..
 - ls $APP_NAME -l
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/$APP_NAME.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/$APP_NAME.tgz"

before_deploy:
 - yarn rollup
 - yarn info qili-app --json > qili-app.json
 - export LATEST=$(node -p "var a=require('./qili-app.json').data['dist-tags']; a ? a.latest : ''")
 - export CURRENT=$(node -p "require('./package.json').version")

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true
 on:
  branch: master
  condition: "$LATEST != $CURRENT"