group: deprecated-2017Q4
language: android
android:
 components:
  - build-tools-23.0.2
  - android-22

addons:
 apt:
  packages:
   - sshpass

before_install:
 - echo "install nodejs"
 - nvm install 8
 - npm install yarn -g
 - node --version
 - npm --version
 - nvm --version
 - pwd

install:
 - yarn install

script:
 - yarn relay
 - yarn api
 - yarn build
 - rm packages/console/dist/index.js
 - mv packages/console/dist/index.html .
 - ls -l
 - yarn cordova -- --storePassword=$STORE_PWD --password=$STORE_PWD
# auto deploy later according to version changes
 - yarn info qili-app --json > qili-app.json
 - export LATEST=$(node -p "require('./qili-app.json').data['dist-tags'].latest")
 - export CURRENT=$(node -p "require('./packages/qili-app/package.json').version")

after_success:
# sync cloud code to qili2.com
 - yarn sync --service $QILI_SERVICE -appId $QILI_APPID --token $QILI_TOKEN
# upload apk
 - mv cordova/platforms/android/build/outputs/apk/android-release.apk ./app.apk
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./app.apk "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"

 - mv index.html packages/console/dist
 - cd packages/console
 - node -p "require('./package.json').version" > dist/app.apk.version
 - mv dist $APP_NAME
 - rm $APP_NAME/config.xml
 - rm $APP_NAME/cordova.html
# upload web pages
 - ls $APP_NAME -l
 - cd $APP_NAME
 - tar cvfz ../$APP_NAME.tgz .
 - cd ..
 - ls -l
 - travis_wait sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $APP_NAME.tgz "$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH"
 - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_USER@$DEPLOY_HOST "tar xvfz $DEPLOY_PATH/$APP_NAME.tgz -C $DEPLOY_PATH && rm $DEPLOY_PATH/$APP_NAME.tgz"
 - pwd
 - cd ../..

before_deploy:
 - pwd
 - cd packages/qili-app

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 skip_cleanup: true
 on:
  branch: master
  condition: "$LATEST != $CURRENT"
