language: node_js
node_js:
 - "4.2"

addons:
 apt:
  packages:
   - sshpass
install:
 - npm install --production

script:
 - echo nothing

after_success:
 - npm run merge
 - sshpass -e -o stricthostkeychecking=no scp dist/allin1.html $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH