language: node_js
node_js:
 - "4.2"

addons:
 apt:
  packages:
   - sshpass
 ssh_known_hosts:
  - $DEPLOY_HOST
install:
 - npm install --production

script:
 - echo nothing

after_success:
 - npm run merge
 - date
 - export SSHPASS=$DEPLOY_PASSWORD
 - sshpass -e scp -o stricthostkeychecking=no dist/allin1.html $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH