import "babel-polyfill"
import * as wechat from "./components/wechat"

export * from "./state"
export * from "./tools/recompose"
export {default as Setting} from "./ui/setting"
export {default as Profile} from "./ui/user-profile"
export {default as Comment} from "./components/comment"
export {default as CommandBar} from "./components/command-bar"
export {default as Empty} from "./components/empty"
export {default as File} from "./components/file"
export {default as Photo} from "./components/photo"
export {default as CheckUpdate} from "./components/check-update"
export {default as Account} from "./components/account"
export {default as InfoForm} from "./components/info-form"
export {wechat}
export {default} from "./app"
